#!/bin/bash
set -e

# Видаляємо старий cookies файл якщо існує (може бути залишок від volume mount)
if [ -f "/tmp/cookies.txt" ]; then
    echo "🗑️  Removing old /tmp/cookies.txt..."
    rm -f /tmp/cookies.txt
fi

# Копіюємо read-only cookies в /tmp/ якщо вони існують
if [ -f "/app/cookies.txt" ]; then
    echo "📋 Copying and fixing cookies from /app/cookies.txt to /tmp/cookies.txt..."
    
    # Конвертуємо cookies в правильний Netscape формат
    python3 - <<'EOF'
import re
import sys

def fix_cookies(input_file, output_file):
    """Конвертує cookies в правильний Netscape формат"""
    
    with open(input_file, 'r') as f:
        content = f.read()
    
    fixed_lines = []
    fixed_lines.append("# Netscape HTTP Cookie File\n")
    fixed_lines.append("# This file was generated by entrypoint.sh\n")
    
    for line in content.split('\n'):
        line = line.strip()
        
        # Skip empty lines and comments
        if not line or line.startswith('#'):
            continue
        
        # Розбиваємо по табуляції або множинних пробілах
        parts = re.split(r'\t+|\s{2,}', line)
        
        if len(parts) >= 7:
            domain = parts[0]
            flag = parts[1] if parts[1] in ['TRUE', 'FALSE'] else 'TRUE'
            path = parts[2]
            secure = parts[3] if parts[3] in ['TRUE', 'FALSE'] else 'FALSE'
            expiration = parts[4]
            name = parts[5]
            # Value може містити пробіли, тому беремо все що залишилось
            value = '\t'.join(parts[6:]) if len(parts) > 7 else parts[6]
            
            # Видаляємо \n з кінця value якщо є
            value = value.rstrip('\n')
            
            # Формуємо правильний рядок
            fixed_line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n"
            fixed_lines.append(fixed_line)
    
    with open(output_file, 'w') as f:
        f.writelines(fixed_lines)
    
    print(f"✅ Fixed {len(fixed_lines) - 2} cookies")

fix_cookies('/app/cookies.txt', '/tmp/cookies.txt')
EOF
    
    chmod 644 /tmp/cookies.txt
    echo "✅ Cookies fixed and copied successfully"
else
    echo "⚠️  Warning: /app/cookies.txt not found, bot will work without cookies"
    echo "   Some platforms may have limitations without authentication"
fi

# Запускаємо основний процес
echo "🚀 Starting YouTube Downloader Bot..."
exec python app.py
